# Generated by Django 3.2.5 on 2021-10-04 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pnna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=122)),
                ('image', models.ImageField(default='', upload_to='images')),
                ('date', models.DateField()),
            ],
        ),
    ]
