# Generated by Django 3.2.5 on 2021-10-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0002_pnna'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=123)),
                ('phone', models.IntegerField(default=91)),
                ('date', models.DateField()),
                ('images', models.ImageField(upload_to='images')),
            ],
        ),
    ]
