# Generated by Django 3.2.5 on 2021-10-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fan', '0003_rail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pnna',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pnna',
            name='image',
        ),
        migrations.AlterField(
            model_name='pnna',
            name='email',
            field=models.CharField(default='', max_length=122),
        ),
        migrations.AlterField(
            model_name='pnna',
            name='phone',
            field=models.CharField(default='', max_length=122),
        ),
    ]
